# Generated by Django 3.2.6 on 2021-08-23 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('bio', models.TextField(blank=True, max_length=100)),
                ('weight', models.IntegerField(blank=True, default=0)),
                ('height', models.IntegerField(blank=True, default=0)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to Say', 'Prefer not to Say')], max_length=30)),
                ('profile_pic', models.ImageField(blank=True, upload_to='images/')),
                ('followers', models.ManyToManyField(blank=True, related_name='user_followers', to='users.Profile')),
                ('following', models.ManyToManyField(blank=True, related_name='user_following', to='users.Profile')),
            ],
        ),
    ]
