# Generated by Django 3.2.6 on 2021-08-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fit',
            name='shown_id',
            field=models.CharField(default='76f25722', editable=False, max_length=32, unique=True),
        ),
    ]
