# Generated by Django 3.2.6 on 2021-08-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='style',
            field=models.CharField(default='main_closet', max_length=50),
        ),
    ]
