# Generated by Django 3.2.6 on 2021-08-11 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fits', '0002_alter_closet_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
