# Generated by Django 3.2.6 on 2021-08-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fits', '0002_alter_fit_shown_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fit',
            name='shown_id',
            field=models.CharField(default='275e6cfc', editable=False, max_length=32, unique=True),
        ),
    ]
