# Generated by Django 3.2.6 on 2021-08-11 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fits', '0003_alter_fit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fit',
            name='id',
            field=models.CharField(default='cda741b2', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
